import { Inter,Figtree,Poppins } from 'next/font/google'
import './globals.css'

const inter = Poppins({ subsets: ['latin'],weight:'400' })
// const inter = Figtree({ subsets: ['latin']})

export const metadata = {
  title: 'StudyNex',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
